### ISSUE TITLE
Screen sharing popup broken in Ubuntu desktop app

### ISSUE THREAD

**Issue by jurgenhaas** [mattermost/mattermost-plugin-jitsi#142] opened 2020-07-24 07:20 UTC
**Mattermost Version** 5.24.2

**Plugin Version** 2.0.0

**Describe the issue**

When clicking bottom left to share screen on Ubuntu desktop app (version 4.5.2) the popup dialog opens but doesn't show any content other than the 2 tabs and a spinning wheel.

Doing the same thing in the browser works just fine.

**Server Error Logs**

n/a

**Desktop App Error Logs**

Looking at the console of the desktop app, this is what gets produced:

```
[LakeDrops] 2020-07-24T07:09:15.553Z [features/desktop-picker] Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
index_bundle.js:42032
[LakeDrops] @atlaskit/modal-dialog: Deprecation warning - Use of the footer prop in ModalDialog is deprecated. Please compose your ModalDialog using the 'components' prop instead
           (anonymous) @ index_bundle.js:42032
           dispatchEvent @ web-view-impl.ts:123
           dispatchEvent @ guest-view-internal.ts:59
           (anonymous) @ guest-view-internal.ts:77
           emit @ events.js:203
           onMessage @ init.ts:50
           index_bundle.js:42036
[LakeDrops] Uncaught (in promise) Error: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
index_bundle.js:42036 [LakeDrops] 2020-07-24T07:09:17.554Z [features/desktop-picker] Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
index_bundle.js:42036 [LakeDrops] Uncaught (in promise) Error: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
index_bundle.js:42036 [LakeDrops] 2020-07-24T07:09:19.554Z [features/desktop-picker] Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
index_bundle.js:42036 [LakeDrops] Uncaught (in promise) Error: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
```

**Screenshots**

![Screenshot from 2020-07-24 09-19-10](https://user-images.githubusercontent.com/1475675/88368661-ce650b00-cd8e-11ea-9969-afc1929dd7d1.png)

**Comment by jespino** [comment] 2020-07-24 09:16
@jurgenhaas thanks for the bug report, this is related to mattermost-desktop app, and the restrictions applied by electron. Our mattermost-desktop team is working on solving it, is going to be solve as part of a future version of mattermost-desktop (If we are  lucky, in the next one).

**Comment by mhamiltonj** [comment] 2020-09-29 17:01
Any timeline for a fix on this? I have the same issue with the desktop client on windows. We're moving our organisation onto Mattermost, the jitsi integration was a part of the rational, but it's not the best user experience if screen sharing appears to be available but doesn't work.

**Comment by larkox** [comment] 2021-01-19 14:27
Duplicate of #121

**Closed by larkox** 2021-01-19 14:27 UTC
Labels: Type/Bug
