### ISSUE TITLE
Embed window share screen don't work on windows 10 mattermost desktop client

### ISSUE THREAD

**Issue by andzejsp** [mattermost/mattermost-plugin-jitsi#189] opened 2021-04-23 06:22 UTC
**Mattermost Windows 10 desktop client Version**
4.7.0-rc2 commit 7b2164f... cant read it in the client and there is no option to copy/paste the version number.

**Mattermost Version**
Mattermost Version: 5.34.1
Database Schema Version: 5.34.0
Database: postgres
Build Hash: fd6693ff5da7e0672269ada78c3e3d408e193e98
EE Build Hash: 2c294523d63cb5947ffa657f2696433772ee9746
Webapp Build Hash: 68476db78ec63fd6d99b55d34894a644eef4e725
Build Date: Thu Apr 15 17:04:10 UTC 2021

**Plugin Version**
Jitsi (jitsi - 2.0.0)

**Describe the issue**
Embed Jitsi video inside Mattermost, cant share my screen or any window. When you press the Share screen button inside the embed window, the share screen selection window pops up and trying to load something but it never loads anything. Jitsi share screen works in web browsers but not in embed window.

**Server Error Logs**
I dont see any errors, nor do i know where and when to look for them.
**Google Chrome Error Logs**
Not used.
**Screenshots**
![Mattermost_2021-04-23_09-19-33](https://user-images.githubusercontent.com/80409979/115831054-c28b9f80-a419-11eb-8f9b-5e48a37482c3.png)
![Mattermost_2021-04-23_09-18-13](https://user-images.githubusercontent.com/80409979/115831071-c91a1700-a419-11eb-95e1-acf282d1072e.png)
![Mattermost_2021-04-23_09-18-53](https://user-images.githubusercontent.com/80409979/115831126-dafbba00-a419-11eb-9e46-10e59b39386e.png)
![Mattermost_2021-04-23_09-19-13](https://user-images.githubusercontent.com/80409979/115831142-ddf6aa80-a419-11eb-91aa-37ffa09fe6e9.png)

https://i.imgur.com/AHCaZBd.png
https://i.imgur.com/9Vf57H2.png
https://i.imgur.com/ENu4llr.png

**Additional context**
Im using self assigned SSL certificates for local hosts, since all im doing right now is testing and looking ways to deploy this inside my workplace.

**Comment by rohit-karthik** [comment] 2021-04-28 02:03
Seems like this is an issue from before... any update? https://github.com/mattermost/mattermost-plugin-jitsi/issues/121

**Comment by hanzei** [comment] 2021-05-27 11:37
Closing as duplicate of https://github.com/mattermost/mattermost-plugin-jitsi/issues/121

**Closed by hanzei** 2021-05-27 11:37 UTC
