### ISSUE TITLE
New idea for the plugin

### ISSUE THREAD

**Issue by PxBCPG** [mattermost/mattermost-plugin-jitsi#168] opened 2020-11-22 11:47 UTC
# New idea for the plugin
I got an idea of improvement for the Jitsi plugin, especially for the call button.
When you currently click on that button, it create a banner in the channel messages. But the problem with that banner is that when you will add some messages, the banner will "disappear" because of the number of messages posted. And the Jitsi call button always link you to the channel Meeting, you can’t really personalize it, and it isn’t necessary. 
    So the idea is to link directly the Jitsi call button with the conference, that mean that when you will click on the button, this will be the same thing as if you click on the "Join Meeting " button, and the also thing to add if possible is the number of participants, but I’m not aware if it is possible. And also, when you click on the button, this won’t create that banner, which will be unuseful, but instead maybe a text message such as "BCPG join the meeting ".

**Comment by larkox** [comment] 2021-01-19 14:37
@PxBCPG is there any chance this is a duplicate of https://github.com/mattermost/mattermost-plugin-jitsi/issues/134 ?

**Comment by hanzei** [comment] 2021-05-27 11:47
Duplicate of #134

**Closed by hanzei** 2021-05-27 11:47 UTC
