### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by thomas-mc-work** [mattermost/mattermost-plugin-jitsi#204] opened 2022-01-18 08:00 UTC
**Describe the issue**

A new release would be lovely. The latest is from Jun 30, 2020 (18 months old as of 2022-01). There appears to be at least some activity in the commit log for 2021. So why should this progress being kept back to the users?

**Comment by hanzei** [comment] 2022-01-21 12:12
Thanks for the reminder @thomas-mc-work :+1: 

Releasing a new version of a plugin requires a non-zero amount of work as the plugin must be tested and approved. The release l logistics also take time. There is a balance between shipping updates to users fast and spending that time to work on other features. 

That being said, it's time for a new Jitsi release. There are currently two outstanding tickets that I would like to include. See https://github.com/mattermost/mattermost-plugin-jitsi/issues/166 for the process.

**Comment by hanzei** [comment] 2022-01-24 19:44
Closing as a duplicate of https://github.com/mattermost/mattermost-plugin-jitsi/issues/166

**Closed by hanzei** 2022-01-24 19:44 UTC
Labels: Duplicate
