### ISSUE TITLE
Update custom status when joining a Jitsi meeting

### ISSUE THREAD

**Issue by olivierlambert** [mattermost/mattermost-plugin-jitsi#188] opened 2021-04-20 09:35 UTC
Since 2 Mattermost release, you can set a custom status. That would be nice to automatically update that status when joining a meeting (eg with a phone emoji), so others will know you are busy.

Or even easier, add the Do Not Disturb status.

**Comment by hanzei** [comment] 2021-05-27 11:53
Duplicate of #143

**Closed by hanzei** 2021-05-27 11:53 UTC
Labels: Difficulty/3:Hard, Help Wanted, Tech/Go, Up For Grabs
